apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 5
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          # enter the path to your image, be sure to include the correct region prefix
          image: william201192/java-sample-app:latest
          #image: ord.ocir.io/axwzmfasnsij/javademodev:cbf64d0141f86ffb43bc1d7719d945884aaa56c1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  #type: LoadBalancer
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-app-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: java-app-service
              port:
                number: 8080
