name: CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Docker image
      run: docker build -t william201192/java-sample-app:${{ github.sha }} .
    - name: Push to DockerHub
      run: docker push william201192/java-sample-app:${{ github.sha }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Update k8s Manifest
      env:
        IMAGE_TAG: ${{ github.sha }}
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        sed "s/\${IMAGE_TAG}/${IMAGE_TAG}/g" deployment-template.yaml > deploy/deployment.yaml
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add deploy/deployment.yaml
        git commit -m "Update deployment to SHA ${IMAGE_TAG}"
        git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}git@github.com:willtechdev/java-sample-app-arm.git HEAD:main